### ISSUE TITLE
Check supporters legal age

### ISSUE THREAD

**Issue by leio10** [podemos-info/decidim-collaborations#12]
They should mark a checkbox to confirm that they are older than a globally configurable age (18 in Spain) and this should also be checked against user born date.

**Comment by jsperezg** [comment]
In order to avoid problems with Data Protection Laws (LOPD and others) Decidim do not stores personal data and, in case there is any persona data stored, then it is hashed. For this reason, in order to be able to validate if a user is over 18 we need a third party API. In Barcelona they've been using the city census. 

If you can provide us with something similar we can study how they have integrated Census with the user authorization feature and look for a solution. Otherwise we can only add a checkbox and trust that the user is saying the truth.
